In [1]:
import numpy as np

RANDOM 

RAND()

In [2]:
var = np.random.rand(5)
var

array([0.9283783 , 0.80800316, 0.59006592, 0.51550163, 0.66787045])

RANDN()

In [3]:
var_1 = np.random.randn(2)
var_1

array([ 0.80372328, -1.59740474])

RANF()

In [4]:
var_2 = np.random.ranf(6)
var_2

array([0.42275605, 0.17888754, 0.52965644, 0.58410027, 0.27953307,
       0.21480312])

RANDINT

In [5]:
var_3 = np.random.randint(1,10,2)
var_3

array([2, 5], dtype=int32)